/*
 * generated by Xtext
 */
package org.osate.ocarina.real.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class REALRuntimeModule extends org.osate.ocarina.real.xtext.AbstractREALRuntimeModule {

}
