// Licensed under the Common Public License (CPL): http://www.eclipse.org/legal/cpl-v10.html
//
// Developed for the US Army under contract W31P4Q-05-AQ-0031
// This software is US Government Unlimited Rights per DFARS
// 252.227-7014.
//
/*
 * generated by Xtext
 */
package org.osate.ocarina.real.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class REALRuntimeModule extends org.osate.ocarina.real.xtext.AbstractREALRuntimeModule {

}
