/*
 * generated by Xtext
 */
package org.osate.ocarina.real.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.osate.ocarina.real.xtext.ui.internal.REALActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class REALExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return REALActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return REALActivator.getInstance().getInjector(REALActivator.ORG_OSATE_OCARINA_REAL_XTEXT_REAL);
	}
	
}
