/*
* Use of the OSATE2-Ocarina plugin is subject to the terms of the license set forth
* at http://www.eclipse.org/legal/cpl-v10.html.
*
* Note: Contributions by user philip.alldredge@uah.edu were performed under contract W31P4Q-05-A-031 for the US Army. 
* These contributions are covered by US Government Unlimited Rights per DFARS 252.227-7014. You are entitled to use this software under the conditions of the Common Public License.
*/
/*
 * generated by Xtext
 */
package org.osate.ocarina.real.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class REALUiModule extends org.osate.ocarina.real.xtext.ui.AbstractREALUiModule {
	public REALUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
