/*
 * generated by Xtext
 */
package org.osate.ocarina.real.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class REALUiModule extends org.osate.ocarina.real.xtext.ui.AbstractREALUiModule {
	public REALUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
