// Licensed under the Common Public License (CPL): http://www.eclipse.org/legal/cpl-v10.html
//
// Developed for the US Army under contract W31P4Q-05-AQ-0031
// This software is US Government Unlimited Rights per DFARS
// 252.227-7014.
//
/*
* generated by Xtext
*/
package org.osate.ocarina.real.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

import org.osate.ocarina.real.xtext.real.ElementBinding;
import org.osate.ocarina.real.xtext.real.EvaluationExpression;
import org.osate.ocarina.real.xtext.real.GenericExpression;
import org.osate.ocarina.real.xtext.real.SelectionExpression;
import org.osate.ocarina.real.xtext.real.SetExpression;
import org.osate.ocarina.real.xtext.real.VerificationExpression;

/**
 * customization of the default outline structure
 * 
 */
public class REALOutlineTreeProvider extends DefaultOutlineTreeProvider {
	// Limit the outline notes
	protected void _createNode(IOutlineNode parentNode, VerificationExpression modelElement) {
	}
	
	protected void _createNode(IOutlineNode parentNode, EvaluationExpression modelElement) {
	}
	
	protected void _createNode(IOutlineNode parentNode, GenericExpression modelElement) {
	}
	
	protected void _createNode(IOutlineNode parentNode, SelectionExpression modelElement) {
	}
	
	protected void _createNode(IOutlineNode parentNode, SetExpression modelElement) {
	}
	
	protected void _createNode(IOutlineNode parentNode, ElementBinding modelElement) {
	}
}
