/*
* generated by Xtext
*/
package org.osate.ocarina.real.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class REALAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/osate/ocarina/real/xtext/parser/antlr/internal/InternalREALParser.tokens");
	}
}
