/*
* generated by Xtext
*/
package org.osate.ocarina.real.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.osate.ocarina.real.xtext.services.REALGrammarAccess;

public class REALParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private REALGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.osate.ocarina.real.xtext.parser.antlr.internal.InternalREALParser createParser(XtextTokenStream stream) {
		return new org.osate.ocarina.real.xtext.parser.antlr.internal.InternalREALParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public REALGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(REALGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
